    ProjectRequestLimit:
      configuration:
        apiVersion: v1
        kind: ProjectRequestLimitConfig
        limits:
        - selector:
            client: alpha
          maxProjects: 0
        - selector:
            client: beta
          maxProjects: 0
        - selector:
            client: common
          maxProjects: 0
    PodNodeSelector:
      configuration:
        podNodeSelectorPluginConfig:
          clusterDefaultNodeSelector: "client=common"
          alpha: client=alpha 
          clusterDefaultNodeSelector: "client=beta"
          beta: client=beta
          clusterDefaultNodeSelector: "client=common"
          common: client=common
