---
-  hosts: masters
   gather_facts: no
   name: Add users to HTPASWD
   tasks:
   -  name: Check for alpha group
      shell: oc get group alpha
      register: result

   -  name: Create Alpha Group
      shell: oc adm groups new alpha
      delegate_to: "{{ groups.masters[0] }}"
      when: result.rc == 1
 
   -  name: Set NodeSelector for Alpha
      shell: oc label groups alpha nodeSelector=alpha
      delegate_to: "{{ groups.masters[0] }}"
      when: result.rc == 1

   -  name: Create user Amy
      htpasswd: 
          path: /etc/origin/master/htpasswd
          name: Amy
          password: 'redhat'

   - name: Add Amy to Alpha group
     shell:  oc adm groups add-users alpha Amy
     delegate_to: "{{ groups.masters[0] }}"
   

#   -  name: Create user Andrew
#      htpasswd:
#          path: /etc/origin/master/htpasswd
#          name: Andrew
#         password: 'redhat'
#   -  name: Create user Brian
#      htpasswd:
#          path: /etc/origin/master/htpasswd
#          name: Brian
#          password: 'redhat'        
#   -  name: Create user Betty 
#      htpasswd:
#          path: /etc/origin/master/htpasswd
#          name: Betty
#          password: 'redhat'
 
