   -  name: Create NFS prometheus exports directory
      file: path=/srv/nfs/{{ volume }} state=directory mode=777 owner=nfsnobody group=nfsnobody
      delegate_to: "{{ groups.nfs[0] }}"

   -  name: Create NFS exports paths
      lineinfile:
        dest: /etc/exports.d/openshift-prometheus.exports
        regexp: "^/srv/nfs/{{ volume }}"
        line: "/srv/nfs/{{ volume }} *(rw,root_squash)"
        create: true
      delegate_to: "{{ groups.nfs[0] }}"

   -  name: reload NFS server
      systemd:
        name: nfs-server
        state: reloaded
      delegate_to: "{{ groups.nfs[0] }}"

   -  name: Create PV definition file
      template:
         src: ../templates/prometheus.j2
         dest: /tmp/{{ volume }}.yml
      delegate_to: "{{ groups.masters[0] }}"

   - name: Create PV{{ volume }} if not exists
     command: oc create -f /tmp/{{ volume }}.yml
     delegate_to: "{{ groups.masters[0] }}"
