---
   -  name: Create user {{ username }} in htpasswd
      htpasswd: 
          path: /etc/origin/master/htpasswd
          name: "{{ username }}"
          password: '{{ password }}'
      delegate_to: "{{ masterhost }}"
      with_items: "{{ groups.masters }}"
      loop_control:
        loop_var: masterhost
    

   -  name: Add {{ username }} to {{ groupname }} group
      shell:  oc adm groups add-users {{ groupname }} {{ username }}
   

